# Generated by Django 5.0.1 on 2024-01-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppCoder", "0002_estudiante"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
