# Generated by Django 5.0.1 on 2024-03-13 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppCoder", "0004_entregable_profesor"),
    ]

    operations = [
        migrations.AddField(
            model_name="entregable",
            name="estudiante",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="AppCoder.estudiante",
            ),
            preserve_default=False,
        ),
    ]
