# Generated by Django 5.0.1 on 2024-03-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppCoder", "0005_entregable_estudiante"),
    ]

    operations = [
        migrations.AddField(
            model_name="profesor",
            name="cursos",
            field=models.ManyToManyField(to="AppCoder.curso"),
        ),
    ]
